addons:
  apt:
    packages:
    - python-pygments
install:
- gem install asciidoctor
- mkdir -p public
- rm -rf public || exit 0
script:
- bin/hugo
deploy:
  provider: s3
  access_key_id: AKIAIANSYJK7WISZBXSA
  secret_access_key:
    secure: hS0pZpj3FK8cnxYywC85pDt7qr6e/LNd0gL+Ii0mF3yP8c5VVfTqSb23uKYpVuwaYXxl5Z2xuhBTjx9JDFVJ4bypdaVB3TwpGqNc97UvA/zJ9n33pqFr6NlildkV0GZVrfb/TAuUXUsYQ4Wt3LgEFMxg4xaRBOlz+tjvCMsYpe0HTeIkV6ofw3RdTj+mWBfuMfgQP206ZXMdOIbAbK/xZengHSSAEghvOEn1QzakbLiP6Z89HFFf6ibWb51L4hDPBw3HsJ3BYSMW4t1WESotkO8yTpOzx0y535KOLhyOxkan6dj4kMmStYLf7LLgZU5t+PmOb7SWSC3FZWnV4tmvUJk1YBdINtbpOKgg9kXXacjNQQZbRehmis8R7RnP223cc+PgSb+XUvPt6CyIta5bymyNEqWWPPxA9Ney5VSuzQm4u9va66zqblCC9MaEYA8dzkrXnBiceMCCDrEpNoVDqS/Alk5e5AEKR/UQBttkgtD0mZ2WqZCYoCa0s4vXXPjOyDH4RnvsA3oQ6/vj0XOi3O5jgZ36O7g+3qXDuhOzT/Zr6liOXalLko9e5UQP9XxxuhQr5hGnmLYwTU6PDzREmi/pvxyC3Xv+hts/fHggSKu7vj+NjHeA1LA5cekITqyR/cCYTx35sajaeMo1MoK4xO1aPGb3iVdhsKK0iN4M4r8=
  bucket: sauerwedding2019
  region: us-east-2
  local-dir: public
  acl: public_read
  on:
    repo: etsauer/wedding-site
  skip_cleanup: true
